final changes
yaricks657/final-project pull request #1
Opened 2024-09-06 06:09 UTC by yaricks657

2024-09-06 11:42 UTC, dirtymew requested changes
Привет Ярослав

хорошая работа 
 - документация
 - логирование
 - задания со *


дал комментарии что поправить и улучшить - есть критичные замечания

2024-09-06 11:42 UTC, dirtymew commented on .gitignore
> +
нужно еще добавит файлы .DS_Store - и удалить из ветки

2024-09-06 11:42 UTC, dirtymew commented on .env
> +JWT_SECRET="secret_key"
TODO_ -префикс стоит у всех переменных приложения поставить

2024-09-06 11:42 UTC, dirtymew commented on Dockerfile
> +COPY go.mod go.sum ./
кажется можно просто COPY . . - так минус одна команда будет

2024-09-06 11:42 UTC, dirtymew commented on Dockerfile
> +FROM ubuntu:latest
стоит взять образ полегче - да и  сразу с go

2024-09-06 11:42 UTC, dirtymew commented on Dockerfile
> +    git \
а зачем это все?

2024-09-06 11:42 UTC, dirtymew commented on README.md
> +    Выполнено все, всключая ВСЕ задания со звездочкой
отлично что дописал документацию

2024-09-06 11:42 UTC, dirtymew commented on tests/settings.go
>  var Token = ``
нужно добавить токен чтобы запускались тесты с авторизацией - они должны проходить

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +	dbFile := filepath.Join(filepath.Dir("./"), "scheduler.db")
кажется что ты не используешь значение TODO_DBFILE

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +	db, err := sql.Open("sqlite3", "./scheduler.db")
тут неверно - нужно везде поправить - критичная ошибка

посмотри как в задании про посылки был организован сторадж

там в структуре хранилось бд - там же можно и логер

Проблема тут в том что ты на каждый зарос открываешь подключение - это плохо
кол-во подключений ограниченно

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +	query := "SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 50"
лимит стоит вынести в константу

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +		tasks = []Task{}
а не понятно почему nil не вернуть... ни или при инициализации сразу пустой слайс сделать...

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +func GetSearchedTasks(mng *manager.Manager, search string) ([]Task, error) {
Рекомендации по рефакторингу - не обязательно но если хочется сделать лучше

- по архитектуре - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10 и в задании про посылки можно подсмотреть как организованы service и storage
- стоит организовать интерфейсы storage service и транспорта 
- интерфейс storage можно соркатить до 4-х методов create update delete find

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +	query := "SELECT id, date, title, comment, repeat FROM scheduler WHERE id = ? LIMIT 1"
LIMIT 1 лишнее

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +	query := "SELECT id, date, title, comment, repeat FROM scheduler WHERE id = ? LIMIT 1"
не может быть 2-х строк с одним id

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +	err = db.QueryRow("SELECT EXISTS(SELECT 1 FROM scheduler WHERE id = ?)", t.Id).Scan(&exists)
лишний запрос - непонятно зачем

одного Update хватит - можно обработать  RowsAffected

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +	err = db.QueryRow("SELECT EXISTS(SELECT 1 FROM scheduler WHERE id = ?)", id).Scan(&exists)
тоже замечание что и для ChangeTask

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/addTask.go
> +	Ttime, _ := time.Parse("20060102", task.Date)
20060102 - вынести в константу и везде использовать

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/addTask.go
> +	if Ttime.Before(today) {
Ttime - плохое имя переменной

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/changeTask.go
> +	addTask := database.Task{
почему addTask - мы же обновляем и зачем эта переменная почему task не подходит

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/changeTask.go
> +		ok, err = task.isRuleValid(today)
очень странно - ok  и ошибка - причем она не обрабатывается

кажется что-то одно нужно возвращать из isRuleValid

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/changeTask.go
> +	ok, err = task.isDateValid()
очень странно - ok и ошибка - причем она не обрабатывается

кажется что-то одно нужно возвращать из isDateValid

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/deleteTask.go
> +	w.Write([]byte("{}"))
_ , _ = w.Write(resp)
тут стоит либо явно проигнорировать ошибку или ее логировать
хорошие линтеры на это ругаться будут и не зря

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/getAllTasks.go
> +	manager.Mng.Log.LogInfo("Поступил запрос на получение всех задач:", r.RequestURI)
прохо писать лог постоянно на всех запросах - так будет каша в логе

выводить в лог стоит только ошибки и warnings

Info писать когда нужно - но так чтобы не забивать логи

подробные логи нужно в уровень TRACE и Debug  - но нужно предусмотреть специальный режим работы приложения

2024-09-06 11:42 UTC, dirtymew commented on internal/database/database.go
> +type Task struct {
кажется что дубли - не понятно зачем это структура если такая-же есть в models

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/addTask.go
> +func AddTask(w http.ResponseWriter, r *http.Request) {
хендлеры стоит в отдельный пакет вынести

2024-09-06 11:42 UTC, dirtymew commented on internal/todo/getSearchedTasks.go
> +package todo
getSearchedTasks.go  - стоит лучше назвать

мб все хендлеры вообще в один файл собрать

2024-09-07 11:09 UTC, yaricks657 commented on tests/settings.go
>  var Token = ``
Могу ошибаться, но в тесте nextdate_3_test.go в куки клиента не записывается токен. Он не проходит единственный из-за авторизации.

2024-09-07 13:00 UTC, yaricks657 commented on internal/database/database.go
> +type Task struct {
У меня возникла зависимость пакетов друг от друга

2024-09-07 13:00 UTC, yaricks657 commented on internal/database/database.go
> +type Task struct {
Дублировал структуры в оба пакета. По-другому можно?

2024-09-07 17:44 UTC, dirtymew commented on internal/database/database.go
> +type Task struct {
да можно просто вынести структуру в отдельный пакет - например model или task

2024-09-07 17:47 UTC, dirtymew approved these changes
Ярослав

задание принимаю 

Поздравляю и желаю удачи

2024-09-07 17:47 UTC, dirtymew commented on internal/database/database.go
> +func AddTask(t *Task, mng *manager.Manager) (string, error) {
AddTask( mng *manager.Manager, t *Task)

но вообще нужно было просто сделать эти методы у Manager ) и или завести структуру storage c зависимостью на Manager

2024-09-08 01:33 UTC, merged